spring.security.oauth2.client:
  registration.auth0:
    #    client-id: <client_id>
    #    client-secret: <client-secret>
    authorization-grant-type: authorization_code
    redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}"
    scope:
      - openid
      - profile
      - email
  provider.auth0:
    #    issuer-uri: https>//<auth0-domain>
    #    authorization-uri: https://<autn0-domain>/authorize
    #    token-uri: https://<autn0-domain>/oauth/token
    #    user-info-uri: https://<autn0-domain>/userinfo
    user-name-attribute: sub
#    jwk-set-uri: https://<autn0-domain>/.well-known/jwks.json